CupcakeMVC/Controllers/CommentController.cs
using CupcakeMVC.Models;
using CupcakeMVC.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace CupcakeMVC.Controllers
{
    public class CommentController : Controller
    {
        public IActionResult Index()
        {
            var userinfo = new UserInfo { Id = 1, Name = "Sabrina", Surname = "Carpenter" };
     
            var comment = new List<Comment>()
            { 
                new Comment() {Comments="What a delicious cake!  "},
                new Comment(){Comments="Your coffees are incredible!"}
            };

            var vm = new UserCommentViewModel();
            vm.userinfo = userinfo;
            vm.comments = comment;

            return View(vm);
        }
    }
}

CupcakeMVC/Controllers/DessertController.cs
using CupcakeMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace CupcakeMVC.Controllers
{
    public class DessertController : Controller
    {
        private readonly IDessertService _service;

        public DessertController(IDessertService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            //it returns list of all desserts
            var data = await _service.GetAll();
            return View(data);
        }
        //Get:Dessert/Create
        [HttpGet]
        public IActionResult Create()
        {
            Dessert dessert=new Dessert();
            return View(dessert);
        }
        [HttpPost]
        public IActionResult Create([Bind("Name,DessertPhotoURL,Description,Price")]Dessert dessert)
        {
            if (!ModelState.IsValid)
            {
                return View(dessert); 
            }
             _service.Add(dessert);
            return RedirectToAction(nameof(Index));
        }
    }
}

CupcakeMVC/Controllers/DoubleMenuController.cs
using CupcakeMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace CupcakeMVC.Controllers
{
    public class DoubleMenuController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DoubleMenuController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var allMenus= _context.DoubleMenus.ToList();
            return View(allMenus);
        }
    }
}

CupcakeMVC/Controllers/DrinksController.cs
using CupcakeMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CupcakeMVC.Controllers
{
    public class DrinksController : Controller
    {
        private readonly IDrinksService _service;

        public DrinksController(IDrinksService service)
        {
            _service = service;
        }
        public async Task< IActionResult> Index()
        {
            var data = await _service.GetAll();
            return View(data);
        }
        [HttpGet]
        public IActionResult Create()
        {
            Drinks drinks = new Drinks();
            return View(drinks);
        }
        [HttpPost]
        public IActionResult Create([Bind("Name,DrinkPhotoURL,Description,Price")] Drinks drinks)
        {
            if (!ModelState.IsValid)
            {
                return View(drinks);
            }
            _service.Add(drinks);
            return RedirectToAction(nameof(Index));
        }
    }
}

CupcakeMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cupcake</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/CupcakeMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/navigation.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <div id="navigation">
        <p class="cupcake"><a style="vertical-align: baseline;font-size: 135px; font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif; position: relative;" asp-area="" asp-controller="Home" asp-action="Index">CUPCAKE.</a></p>
        <ul id="nav">
            <li><a asp-area="" asp-controller="Dessert" asp-action="Index">Desserts</a></li>
            <li><a asp-area="" asp-controller="Drinks" asp-action="Index">Drinks </a></li>
            <li><a asp-area="" asp-controller="DoubleMenu" asp-action="Index">Promotional Menus </a></li>
            <li><a asp-area="" asp-controller="Comment" asp-action="Index">Comments </a></li>
        </ul>

    </div>


    <div>
        @RenderBody()
    </div>

    @*<div id="footer">

        <p>Copyright 2023 by SUGAR & SPYKE </p>

    </div>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

CupcakeMVC/Views/Shared/_addPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<div style="position:fixed; right:25px; bottom:25px;" class="text-white">
    <a asp-controller="Drinks" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i>Add new Drink
    </a>
    <a asp-controller="Dessert" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i>Add new Dessert
    </a>
</div>